### ISSUE TITLE
[Bug] Unable to ingest Databricks Unity Catalog lineage after upgrading from 1.10.4 to 1.11.13

### ISSUE THREAD

**Issue by gracezhangawx** [open-metadata/OpenMetadata#26800]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?  -- Ingestion

**Describe the bug**

- The Unity Catalog tables lineage cannot be ingested after I upgrade OM from 1.10.4 to 1.11.13
- The error is : GetQueries-No valid authentication settings. Please provide an access token.
- I have tried both OAuth and Token authentication (token with all_apis access), but neither is successfully

Logs:

> [2026-03-23, 10:47:20 UTC] {test_connections.py:203} INFO - Running GetQueries...
[2026-03-23, 10:47:20 UTC] {test_connections.py:213} DEBUG - Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/ingestion/source/connections.py", line 131, in test_connection_common
    result = test_connection_fn(metadata)
TypeError: test_connection() missing 2 required positional arguments: 'connection' and 'service_connection'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/ingestion/connections/test_connections.py", line 204, in _test_connection_steps_during_ingestion
    step.function()
  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/ingestion/source/database/unitycatalog/connection.py", line 193, in test_lineage_tables
    with engine.connect() as conn:
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 145, in _do_get
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/impl.py", line 143, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 690, in __connect
    with util.safe_reraise():
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.10/site-packages/databricks/sql/__init__.py", line 48, in connect
    return Connection(server_hostname, http_path, access_token, **kwargs)
  File "/home/airflow/.local/lib/python3.10/site-packages/databricks/sql/client.py", line 100, in __init__
    raise ValueError("No valid authentication settings. Please provide an access token.")
ValueError: No valid authentication settings. Please provide an access token.
[2026-03-23, 10:47:20 UTC] {test_connections.py:214} ERROR - GetQueries-No valid authentication settings. Please provide an access token.

<img width="1448" height="1684" alt="Image" src="https://github.com/user-attachments/assets/d7f72f61-13b6-4542-90a4-df7a3cc17673" />

**To Reproduce**

Screenshots or steps to reproduce

**Expected behavior**

Can ingest Unity Catalog lineage successfully.

**Version:**
 - Python version:
 - OpenMetadata version: 1.11.13
 - OpenMetadata Ingestion package version: openmetadata-ingestion[databricks]==1.11.13

**Additional context**

**Comment by gracezhangawx** [comment]
Since the new version retrieves Unity Catalog lineage from system tables rather than the API, is the existing access check still valid?

**Comment by gracezhangawx** [comment]
Reopen it since closed it by mistake

**Comment by gracezhangawx** [comment]
> Reopen it since closed it by mistake

Hi @harshach , I'm confused why I cannot reopen it ...
