### ISSUE TITLE
module 'sqlalchemy.types' has no attribute 'DOUBLE'

### ISSUE THREAD

**Issue by piby180** [open-metadata/OpenMetadata#27348]
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
ingestion

**Describe the bug**

sqlalchemy.type.DOUBLE works with sqlalchemy >= 2.0.0. But the sqlalchemy = 1.4.54 is installed in openmetadata/ingestion=1.12.5

This causes issue here
https://github.com/open-metadata/OpenMetadata/blob/cfd71e8bd38129a85fa4ab6d9ae3da67e166033a/ingestion/src/metadata/ingestion/source/database/pinotdb/metadata.py#L33

Also, pinotdb=5.7.0 is pretty old and it should be updated to the latest version (9.1.1)

````
> processor='yield_table' nullable=False must_return=False overwrite=True consumer=['database_service', 'database', 'database_schema'] context='table' store_all_in_context=False clear_context=False store_fqn=False cache_entities=False use_cache=True
[2026-04-14 09:30:05] DEBUG    {metadata.Ingestion:sql_column_handler:296} - Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/ingestion/source/database/sql_column_handler.py", line 292, in get_columns_and_constraints
    columns = self._get_columns_internal(
  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/ingestion/source/database/sql_column_handler.py", line 238, in _get_columns_internal
    return inspector.get_columns(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/reflection.py", line 497, in get_columns
    col_defs = self.dialect.get_columns(
  File "/home/airflow/.local/lib/python3.10/site-packages/pinotdb/sqlalchemy.py", line 280, in get_columns
    columns = [
  File "/home/airflow/.local/lib/python3.10/site-packages/pinotdb/sqlalchemy.py", line 283, in <listcomp>
    "type": get_type(spec["dataType"], spec.get("fieldSize")),
  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/ingestion/source/database/pinotdb/metadata.py", line 33, in get_type_custom
    "double": types.DOUBLE,
AttributeError: module 'sqlalchemy.types' has no attribute 'DOUBLE'

````

**To Reproduce**

Screenshots or steps to reproduce

Use openmetadata/ingestion=1.12.5 and try to ingest pinot tables to OM

**Expected behavior**

This bug should be resolved

**Version:**
 - OS: [e.g. iOS] Docker
 - Python version: 3.10.19
 - OpenMetadata version: [e.g. 0.8] 1.12.5
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`] `openmetadata-ingestion[docker]==1.12.5`

**Additional context**
Slack Thread : https://openmetadata.slack.com/archives/C02B6955S4S/p1776160249872429

**Comment by piby180** [comment]
This relates to the following commit. 
https://github.com/open-metadata/OpenMetadata/commit/5eb553a251ef0992afc0ee6e7920c4311bd1b990

sqlalchemy >= 2.0.0 in order to use types.DOUBLE

**Comment by mohitjeswani01** [comment]
hey @piby180 @nikhilchennam may i work on this issue ?

**Comment by ulixius9** [comment]
closing by https://github.com/open-metadata/OpenMetadata/pull/27367
