### ISSUE TITLE
Airflow Lineage Parsing Failure

### ISSUE THREAD

**Issue by joswlv** [open-metadata/OpenMetadata#3410]
**Affected module**
Ingestion Framework

**Describe the bug**
I am using airflow integrated with openmetadata. 
There is a problem in parsing the DAG lineage.
Failed to parse `start_date`, so it is not possible to transmit lineage data to openmetadata.
Below is the failure log recorded in airflow.

```
[2022-03-14 04:59:16,712] {utils.py:267} INFO - Task Properties {'start_date': 1639839600.0, '_outlets': [], 'email': 'dev_data@xxx.net', '_inlets': [], 'task_id': 'xxx_prediction', '_downstream_task_ids': ['sensor', 'xxx_inference_sensor', 'inference_sensor'], 'label': 'xxx_prediction', '_task_type': 'AirflowEmrOperator', '_task_module': 'xxxxx', 'wait_for_downstream': False, 'trigger_rule': 'all_success', 'execution_timeout': None, 'depends_on_past': False, 'sla': None, 'end_date': None}
[2022-03-14 04:59:16,712] {utils.py:268} INFO - DAG properties {'timezone': 'Asia/Seoul', 'catchup': False, 'fileloc': 'xxxx.py', 'tags': ['weekly'], '_concurrency': 64, 'start_date': None, '_default_view': 'tree', '_access_control': None, 'is_paused_upon_creation': None}
[2022-03-14 04:59:16,713] {utils.py:328} INFO - Get Airflow Service ID
[2022-03-14 04:59:16,869] {utils.py:310} ERROR - Failed to parse Airflow DAG task and publish to OpenMetadata due to 'float' object has no attribute 'timestamp'
[2022-03-14 04:59:16,870] {utils.py:313} ERROR - Traceback (most recent call last):
  File "/home/***/.local/lib/python3.8/site-packages/***_provider_openmetadata/lineage/utils.py", line 275, in parse_lineage_to_openmetadata
    pipeline = create_pipeline_entity(
  File "/home/***/.local/lib/python3.8/site-packages/***_provider_openmetadata/lineage/utils.py", line 202, in create_pipeline_entity
    task_start_date, task_end_date = iso_task_start_end_date(task_properties)
  File "/home/***/.local/lib/python3.8/site-packages/***_provider_openmetadata/lineage/utils.py", line 163, in iso_task_start_end_date
    convert_epoch_to_iso(int(props["start_date"].timestamp()))
AttributeError: 'float' object has no attribute 'timestamp'
```

**Version:**
 - OpenMetadata version: 0.8.2
 - OpenMetadata Ingestion package version: 0.8.12

**Comment by harshach** [comment]
@pmbrull I think this is fixed. Can you double-check and close it out

**Comment by pmbrull** [comment]
Working in 0.10
