### ISSUE TITLE
Nifi 2.x is not working

### ISSUE THREAD

**Issue by ItsNicolai** [open-metadata/OpenMetadata#22642]
I am unable to establish a connection from OpenMetadata to Apache NiFi 2.x. 
The integration works perfectly with NiFi 1.x, but after upgrading to 2.x, all attempts to connect fail. 
Based on my debugging, it appears that the NiFi 2.x API has undergone changes compared to 1.x, which makes the current OpenMetadata connector incompatible.

I have tried various configurations, including adjusting authentication settings but none have succeeded.

Ideally, the connector should detect and work with both 1.x and 2.x versions, adapting to the API differences.

Nifi versions which I've tried:

1.28.1 -> Works
2.4.0 -> Didn't work

Error from 2.4.0:

`Internal Server Error and response {"error": "Error running automation workflow due to [404 Client Error: Not Found for url: https://172.31.1.1:9443/nifi-api/access] "}`

**Comment by AngelitoMA11** [comment]
How do u connect to NiFi? All time the error is the same for me:

test-connection-Nifi-TkAkQIZg Failed to trigger workflow due to airflow API returned Internal Server Error and response {"error": "Error running automation workflow due to [404 Client Error: Not Found for url: https://9.234.541453:8443/nifi-api/access/token] "} 

Or:

test-connection-Nifi-jQ8iTHJ0 Failed to trigger workflow due to airflow API returned Internal Server Error and response {"error": "Error running automation workflow due to ['NoneType' object has no attribute 'text'] "}

I try it with Nifi Basic Auth and Nifi Client Certificate Auth, the error is the same for both
