### PR TITLE
Fixes #27348: handle Pinot DOUBLE mapping across SQLAlchemy versions

### LINKED ISSUE #27348: module 'sqlalchemy.types' has no attribute 'DOUBLE'
**Affected module**
Does it impact the UI, backend or Ingestion Framework?
ingestion

**Describe the bug**

sqlalchemy.type.DOUBLE works with sqlalchemy >= 2.0.0. But the sqlalchemy = 1.4.54 is installed in openmetadata/ingestion=1.12.5

This causes issue here
https://github.com/open-metadata/OpenMetadata/blob/cfd71e8bd38129a85fa4ab6d9ae3da67e166033a/ingestion/src/metadata/ingestion/source/database/pinotdb/metadata.py#L33

Also, pinotdb=5.7.0 is pretty old and it should be updated to the latest version (9.1.1)

````
> processor='yield_table' nullable=False must_return=False overwrite=True consumer=['database_service', 'database', 'database_schema'] context='table' store_all_in_context=False clear_context=False store_fqn=False cache_entities=False use_cache=True
[2026-04-14 09:30:05] DEBUG    {metadata.Ingestion:sql_column_handler:296} - Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/ingestion/source/database/sql_column_handler.py", line 292, in get_columns_and_constraints
    columns = self._get_columns_internal(
  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/ingestion/source/database/sql_column_handler.py", line 238, in _get_columns_internal
    return inspector.get_columns(
  File "/home/airflow/.local/lib/python3.10/site-packages/sqlalchemy/engine/reflection.py", line 497, in get_columns
    col_defs = self.dialect.get_columns(
  File "/home/airflow/.local/lib/python3.10/site-packages/pinotdb/sqlalchemy.py", line 280, in get_columns
    columns = [
  File "/home/airflow/.local/lib/python3.10/site-packages/pinotdb/sqlalchemy.py", line 283, in <listcomp>
    "type": get_type(spec["dataType"], spec.get("fieldSize")),
  File "/home/airflow/.local/lib/python3.10/site-packages/metadata/ingestion/source/database/pinotdb/metadata.py", line 33, in get_type_custom
    "double": types.DOUBLE,
AttributeError: module 'sqlalchemy.types' has no attribute 'DOUBLE'

````

**To Reproduce**

Screenshots or steps to reproduce

Use openmetadata/ingestion=1.12.5 and try to ingest pinot tables to OM

**Expected behavior**

This bug should be resolved

**Version:**
 - OS: [e.g. iOS] Docker
 - Python version: 3.10.19
 - OpenMetadata version: [e.g. 0.8] 1.12.5
 - OpenMetadata Ingestion package version: [e.g. `openmetadata-ingestion[docker]==XYZ`] `openmetadata-ingestion[docker]==1.12.5`

**Additional context**
Slack Thread : https://openmetadata.slack.com/archives/C02B6955S4S/p1776160249872429

### PR DESCRIPTION
**Pull request by harishkotra**
## Summary
- fix Pinot type mapping to avoid `types.DOUBLE` hard dependency that breaks on SQLAlchemy 1.4
- use a compatibility fallback chain: `types.DOUBLE` -> `sqltypes.DOUBLE` -> `types.Float`
- update Pinot unit test expectation for `double` to allow SQLAlchemy-version-safe floating mapping while preventing integer regressions

## Validation
- ran targeted test:
  - `./.venv311/bin/python -m pytest ingestion/tests/unit/topology/database/test_pinotdb.py -q`
- result: `10 passed`

## Notes
- this directly addresses the ingestion failure reported in #27348 (`AttributeError: module sqlalchemy.types has no attribute DOUBLE`).

----
## Summary by Gitar

- **Feature inclusions:**
  - The PR includes several unrelated commits merged into the branch, such as `fix(search): scope alias lookups`, `feat(queryRunner): raise maxResultSize`, and `fix(domains): fix flaky Rename domain`.
  - These changes appear to be side effects of merging `main` into the feature branch rather than the intent of the PR.

<sub>This will update automatically on new commits.</sub>

### CODE REVIEW

**Comment by edg956** [comment]
Hi @harishkotra! Thank you for your contribution. The change looks good to me although I think the AI suggestions are both good. Could you please update your PR so I can trigger the CI?

**Comment by harishkotra** [comment]
Updated per feedback: applied both suggestions (moved DOUBLE fallback resolution to module level and adjusted assertion order in the regression test), then re-ran the targeted Pinot test (10 passed). Ready for CI trigger @edg956

**Review by edg956 — DISMISSED** [review]

**Comment by edg956** [comment]
> **The Python checkstyle failed.**
> 
> Please run `make py_format` and `py_format_check` in the root of your repository and commit the changes to this PR. You can also use [pre-commit](https://pre-commit.com/) to automate the Python code formatting.
> 
> You can install the pre-commit hooks with `make install_test precommit_install`.

@harishkotra could you please review this?

**Comment by harishkotra** [comment]
Updated this PR per review feedback:
- merged latest main into this branch (it was out-of-date)
- ran make py_format
- ran make py_format_check

Committed and pushed the formatting/base-sync updates @edg956

**Comment by edg956** [comment]
Thanks @harishkotra. I've rebased main so keep that in mind if any more change is needed on your end as you'll have to sync your local environment first.

I've just approved the workflow. Hopefully we'll get everything green 🤞🏼

**Review by edg956 — APPROVED** [review]

**Comment by edg956** [comment]
@harishkotra there's some infrastructure flakiness in the pytest workflow I'm trying to get past by retrying and there is a playwright test broken from upstream I'm working on right now to unblock this PR

**Comment by harishkotra** [comment]
> @harishkotra there's some infrastructure flakiness in the pytest workflow I'm trying to get past by retrying and there is a playwright test broken from upstream I'm working on right now to unblock this PR

Appreciate the reponse and thank you for the support.

**Comment by edg956** [comment]
@harishkotra thank you for your contribution! Let me confirm whether this will make it to 1.12.6 or the next release

**Comment by harishkotra** [comment]
> @harishkotra thank you for your contribution! Let me confirm whether this will make it to 1.12.6 or the next release

Amazing! Absolutely delight to be contributing to this project. Thanks for all the support @edg956
