### ISSUE TITLE
Regression in v1.13.0: AzureSQL ingestion crashes on bigint columns (sqlalchemy.util.compat error)

### ISSUE THREAD

**Issue by elindbo** [open-metadata/OpenMetadata#30514]
### Connector

AzureSQL 

### Feature area

Metadata ingestion

### Describe the bug

Reporting a bug, Regression in v1.13.0: AzureSQL ingestion crashes on bigint columns (sqlalchemy.util.compat error)

Hi team! :wave: We are running into a blocker with the AzureSQL metadata ingestion in v1.13.0, which seems to be a regression, as it worked perfectly on our environments running v1.12.6.

The Issue: When the ingestion agent hits tables containing bigint columns, it crashes and fails to fetch any columns for that table. It appears to be a SQLAlchemy 2.0 compatibility issue with the underlying pyodbc driver looking for the deprecated long_type.

Error Log: Unexpected exception getting columns for table [table_name] (schema: 'dbo', db: '...'): module 'sqlalchemy.util.compat' has no attribute 'long_type'

Our Constraints (Why we can't use the pymssql workaround): We know the generic MSSQL connector (using pymssql) handles this without issues. However, our strict enterprise security architecture mandates the use of Azure AD Service Principals for authentication.

Since pymssql doesn't support Service Principals, we are locked into using the AzureSQL connector (pyodbc), which currently crashes on these tables.

Has anyone else encountered this on 1.13.0, or is there a patch in the pipeline for this SQLAlchemy 2.0 / pyodbc conflict?

I asked if this will be fixed in v.1.13.1 but received a reply to create a new ticket, via the conversation in Slack with @nikhilchennam 
Thanks in advance!
Søren

### To Reproduce

Steps to reproduce:

Use OMD v1.13.0.
Set up an AzureSQL connection (using Client ID / Secret).
Attempt to ingest a table containing a bigint column.

### Expected behavior

Does not ingest tables which contains BIGINT and will not ingest any tables that have it. Leaving the rest of the table blank.

### Connection / ingestion config

```yaml

```

### Logs

```shell
[2026-07-28 08:14:22] INFO     {metadata.Ingestion:common_db_source:151} - Ingesting from database: sqldb_ubbi_production
[2026-07-28 08:14:23] INFO     {metadata.Ingestion:common_db_source:804} - Processing schema: dbo
[2026-07-28 08:14:24] INFO     {metadata.Ingestion:common_db_source:825} - Processing table: booking
[2026-07-28 08:14:24] ERROR    {metadata.Ingestion:common_db_source:445} - Failed to fetch columns for table 'booking' in schema 'dbo'
Traceback (most recent call last):
  File "/home/openmetadata/.local/lib/python3.10/site-packages/metadata/ingestion/source/database/common_db_source.py", line 430, in get_columns
    columns = self.inspector.get_columns(table_name, schema_name)
  File "/home/openmetadata/.local/lib/python3.10/site-packages/sqlalchemy/engine/reflection.py", line 450, in get_columns
    return self.dialect.get_columns(self.bind, table_name, schema, info_cache=self.info_cache, **kw)
  File "/home/openmetadata/.local/lib/python3.10/site-packages/sqlalchemy/dialects/mssql/pyodbc.py", line 398, in get_columns
    coltype = self._resolve_type(type_name, length, precision, scale)
  File "/home/openmetadata/.local/lib/python3.10/site-packages/sqlalchemy/dialects/mssql/base.py", line 2510, in _resolve_type
    return sqltypes.long_type()
AttributeError: module 'sqlalchemy.sql.sqltypes' has no attribute 'long_type'
[2026-07-28 08:14:24] WARNING  {metadata.Ingestion:common_db_source:484} - Skipping rest of table 'booking' due to schema inspection error.
[2026-07-28 08:14:24] INFO     {metadata.Ingestion:common_db_source:825} - Processing table: scan
```

### OS
Deployment: Kubernetes (Native K8s ingestion engine, Airflow disabled)

Ingestion Container OS: Official OpenMetadata Docker Image (Linux / Python 3.10.20)

OpenMetadata Server Version: 1.13.1

OpenMetadata Ingestion Package: 1.13.0.0

Target Database: AzureSQL (Authenticating via Entra ID / Service Principal)

### Python version

3.10

### OpenMetadata version

1.13.0

### OpenMetadata Ingestion package version

[2026-07-28 08:36:45] INFO     {metadata.OMetaAPI:server_mixin:97} - OpenMetadata client running with Server version [1.13.1] and Client version [1.13.0.0]

### Additional context

For context, here is the typical traceback when the ingestion agent inspects a table containing a BIGINT column. It crashes on the SQLAlchemy 2.x long_type removal, effectively skipping all columns for that table:

### Pre-submission checklist

- [x] I searched for duplicate issues.
- [x] I removed credentials, hostnames, emails, and other sensitive data from logs and config.

**Comment by elindbo** [comment]
Also found same issue in v.1.13.1. since submitting this @nikhilchennam Thank you for showing me where to report this.

**Comment by elindbo** [comment]
We now believe this is something the core team with access to the OpenMetadata Docker image can fix, as it relates directly to the changes mentioned in the 1.13.0 release notes.

**Root Cause:**
The 1.13 release carried out a massive major version bump of underlying libraries, explicitly stating: *"Key dependencies: SQLAlchemy 2.x, pandas 2.1.x, pyodbc 5.3.x"*.

During the upgrade from SQLAlchemy 1.4 to 2.x, legacy code was removed, including the `long_type` module which handled large numbers in older versions of Python. The issue occurs because the `pyodbc` driver (used by the AzureSQL connector) is still looking for this old `long_type` when it encounters a `BIGINT` column. Since that module was removed in SQLAlchemy 2.0, the entire ingestion agent crashes. Essentially, the framework upgrade inadvertently broke AzureSQL compatibility in 1.13.0.

As a logistics broker, our production databases are heavily populated with massive transaction IDs, package numbers, and system keys that far exceed the standard `INT` limit, making `BIGINT` mandatory for our architecture. Because of our strict security requirements, we must use Azure Active Directory (Service Principals) for authentication. This locks us to the AzureSQL connector, meaning we cannot just switch to the generic MSSQL connector. Our only current workaround is the massive task of manually building and maintaining shadow SQL Views to cast all `BIGINT` columns, which is not sustainable long-term. (They will be trasnformed to VARCHAR or NUMERIC/DECIMAL (19,0)).

**Proposed fix:**
We suspect that fixing the type mapping for the `pyodbc` driver within the AzureSQL connector will solve the problem. If the connector is updated to natively recognize and map `BIGINT` under the new SQLAlchemy 2.0 engine, the agent should run smoothly again.

**Comment by elindbo** [comment]
Updated with further OS and logfile information.

**Comment by ulixius9** [comment]
fixed by version 1.13.2 https://github.com/open-metadata/OpenMetadata/pull/29639

**Comment by elindbo** [comment]
We have tested and it does not fail anymore. Thank you for the fix!
