### ISSUE TITLE
py-tests red on Python 3.10: pygtrie 2.6.0 breaks `import airflow` (cannot import name 'Connection' from 'airflow.models')

### ISSUE THREAD

**Issue by Khairajani** [open-metadata/OpenMetadata#32377]
### Affected module

Ingestion Framework / CI

### Describe the bug

Every `py-tests` run that resolves dependencies after **2026-09-01T11:06Z** fails on the Python 3.10 lane with:

```
ImportError: cannot import name 'Connection' from 'airflow.models'
```

- `python / Unit Tests & Static Checks (3.10)` — 3 failures in `tests/unit/topology/pipeline/test_airflow_connection.py` plus a collection error on `tests/unit/source/pipeline/airflow/test_connection.py`
- `python / Integration Tests (shard-3, 3.10)` — collection error on `tests/integration/airflow/test_lineage_runner.py`

3.11 and 3.12 are unaffected. Because 3.10 is `MAIN_PYTHON_VERSION`, `py-tests-status` goes red and the merge queue evicts every PR that touches `ingestion/`.

### Root cause

Not a code change. `pygtrie 2.6.0` was published to PyPI at 2026-09-01T11:06:08Z. It annotates with `typing.Self` (PEP 673, Python 3.11+) but declares **no `requires-python` floor**, so pip and uv install it on 3.10, where importing it raises:

```
$ python3.10 -c "import pygtrie"
AttributeError: module 'typing' has no attribute 'Self'   # pygtrie.py:83, `def __copy__(self) -> _t.Self`
$ python3.13 -c "import pygtrie"   # fine
```

`apache-airflow-core` and `apache-airflow-task-sdk` both require `pygtrie>=2.5.0` with no ceiling, and `airflow._shared.logging.structlog` imports it at module level. The import chain:

```
metadata/ingestion/source/pipeline/airflow/connection.py:31  from airflow import __version__
 -> airflow/__init__.py:64                                   from airflow import configuration, settings
   -> airflow/configuration.py:822                           (module level)
     -> initialize_secrets_backends()  [:768]                from airflow.models import Connection
       -> airflow/_shared/logging/structlog.py:33            import pygtrie
         -> pygtrie 2.6.0                                    AttributeError: typing has no attribute 'Self'
   => surfaced by the lazy-attribute machinery as
      ImportError: cannot import name 'Connection' from 'airflow.models'
```

### Evidence

Diffing the full installed package set between the last passing 3.10 unit job and the first failing one leaves one meaningful delta:

| | pass (09:44Z) | fail (11:41Z) |
|---|---|---|
| **pygtrie** | **2.5.0** | **2.6.0** |
| fabric | 3.2.2 | 3.2.3 |
| invoke | — | 2.2.1 |

`apache-airflow`, `apache-airflow-core` and `apache-airflow-task-sdk` are identical (3.3.1 / 3.3.1 / 1.3.1) in both. fabric and invoke are resolver noise — fabric 3.2.3 shipped in April, and either would affect all three Python lanes equally.

The timeline is consistent: every run resolving before 11:06Z passed, every one after failed. One PR went through the merge queue four times on the same content — 08:34 pass, 08:45 pass, 09:44 pass, 11:41 fail. Only one commit landed on `main` after 08:00Z, at 12:56Z, i.e. after the first failures.

### Expected behavior

`py-tests` green on 3.10.

### Fix

Cap `pygtrie<2.6` in `ingestion/setup.py`. Note `ingestion/airflow-constraints-3.3.1.txt` already pins `pygtrie==2.5.0`, but the unit-test install path does not apply that constraints file, which is why it did not protect CI.

Upstream this belongs to pygtrie (declare `requires-python>=3.11`, or use `typing_extensions.Self`) and to Airflow (cap the dependency). The pin can be dropped once either lands, or once 3.10 support is dropped.

### OpenMetadata version

main (2.0.0-SNAPSHOT); also affects 1.13 and 2.0 branches, which build on 3.10.
